### ISSUE TITLE
Odin container immediately exits 0

### ISSUE THREAD

**Issue by Jafner** [memgraph/odin#2] opened 2023-09-21 20:47 UTC
Following the steps described in the setup docs, the memgraph and bor containers appear to launch and run fine, but the odin container exits with the following log text:  

```
odin      | Lifecycle scripts included in magic-graph@1.0.0:
odin      |   version
odin      |     node version-bump.mjs && git add manifest.json versions.json
odin      |
odin      | available via `npm run-script`:
odin      |
odin      |   dev
odin      |     node esbuild.config.mjs
odin      |   build
odin      |     tsc -noEmit -skipLibCheck && node esbuild.config.mjs production
odin      |
odin      |
odin exited with code 0
```

No changes were made to the docker-compose file.  

This is running Docker Desktop on Windows 11.

**Comment by howie-serious** [comment] 2023-09-26 06:01
same problem here.
<img width="1223" alt="CleanShot 2023-09-26 at 14 00 59@2x" src="https://github.com/memgraph/odin/assets/17040190/b202e286-6b5a-449a-b801-d049d98d2af1">

**Comment by matayaaa** [comment] 2023-09-27 06:35
Same. I've been playing around for hours now and can't get ODIN working. 

Also seeing this in terminal.. "WARN[0000] The "MOCK" variable is not set. Defaulting to a blank string. " 

Can see plugin successfully installed but it will not load

**Comment by crendl** [comment] 2023-10-02 11:44
same here! 
the plugin is visible within obsidian, but can't be enabled (failed to load plugin ODIN).

**Comment by trunksio** [comment] 2023-10-08 09:33
Same here - but on OSX other two containers running but Odin exited.

**Comment by danielbackus** [comment] 2023-11-08 15:46
FYI I experienced this issue but was able to resolve it.

It appears the Odin container is intended to exit as it simply uses esbuild to compile the plugin which Obsidian consumes. However, it doesn't seem to actually work. I just manually called the build script (i.e. `npm run build`), and then I was able to enable the plugin in Obsidian.

After this, calls to OpenAI API still were failing until I added `LLM_MODEL_NAME=chatgpt4` environment to the `bor` container in the `docker-compose.yml`.

After this, calls to OpenAI API began succeeding but I still can't see any output in Obsidian. If/when I have time, next step is to dig further into the backend code at https://github.com/memgraph/bor to see what's happening.

**Comment by AlexIchenskiy** [comment] 2024-03-06 07:29
Hello everyone and thank you for your interest in Odin! I'm happy to announce that I've managed to fix this issue. Despite Odin still being considerably unstable, Docker and Docker Compose should now work as intended. I'm closing this issue as completed, but please feel free to open new issues and contribute to Odin and [Bor](https://github.com/memgraph/bor). Your contributions can help make Odin better. Special thanks to @danielbackus - looking forward to seeing your contributions :) Any input is highly appreciated!

**Closed by AlexIchenskiy** 2024-03-06 07:29 UTC
