### ISSUE TITLE
Plans to Support other LLMs?

### ISSUE THREAD

**Issue by DeveloperPaul123** [memgraph/odin#1] opened 2023-09-21 16:27 UTC
ChatGPT is great, but it would be nice to also have the option to use local models via something like [llama.cpp](https://github.com/ggerganov/llama.cpp). Is this something that you are interested in incorporating?

**Comment by sammcj** [comment] 2023-09-21 21:01
Came to ask the same, it would be great if you didn't have to use "Open"AI's products with your data, especially when we're able to run some pretty neat and fine-tunable models locally / on our own servers now with decent APIs, libraries etc...

**Comment by ishaan-jaff** [comment] 2023-09-22 17:14
Hi @DeveloperPaul123 @sammcj I believe we can help with this issue. I’m the maintainer of LiteLLM https://github.com/BerriAI/litellm

**TLDR:**
**We allow you to use any LLM as a drop in replacement for `gpt-3.5-turbo`. 
You can use our proxy server or spin up your own proxy server using LiteLLM**

## Usage
This calls the provider API directly

```python
from litellm import completion
import os
## set ENV variables 
os.environ["OPENAI_API_KEY"] = "your-key" # 
messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# falcon call
response = completion(model="falcon-40b", messages=messages)
```

**Comment by DeveloperPaul123** [comment] 2023-09-22 19:01
@ishaan-jaff 

This is not something I'm interested in. I want to run the LLM locally, directly on my local machine without having to spin up my own server; even if it's a local server.

**Comment by ishaan-jaff** [comment] 2023-09-23 17:07
@DeveloperPaul123 I'd recommend checking out ollama for this https://ollama.ai/

**Comment by AlexIchenskiy** [comment] 2024-03-06 06:57
Thanks everyone for your input! Currently, adding support for other LLMs isn't possible in ODIN. I've raised Issue #7 to track this feature request. You're welcome to contribute to implementing this feature!

Closing this PR as a duplicate of Issue #7.

**Closed by AlexIchenskiy** 2024-03-06 06:57 UTC
